//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appium.Net.Sandbox.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class App : global::System.Configuration.ApplicationSettingsBase {
        
        private static App defaultInstance = ((App)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new App())));
        
        public static App Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1:4723/wd/hub")]
        public string Url {
            get {
                return ((string)(this["Url"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#love #TagsForLikes #TagsForLikesApp #tweegram #photooftheday #amazing #smile #fo" +
            "llow4follow #like4like #look #instalike #food #instadaily #instafollow #followme" +
            " #instagood #bestoftheday #instacool #instago #follow #webstagram #colorful #sty" +
            "le #swag")]
        public string TempHashs {
            get {
                return ((string)(this["TempHashs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>#erarta #erarta_art #museum #spb #saintpetersburg #russia</string>\r\n  <str" +
            "ing>#regentspark #london #uk #greatbritain #londonisthecapitalofgreatbritain #wt" +
            "f #is #this</string>\r\n  <string>#london #uk #thecamdenhead #awesome #smokingburg" +
            "ers #greatbritain #londonisthecapitalofgreatbritain</string>\r\n  <string>#london " +
            "#uk #greatbritain #catholic #church #londonisthecapitalofgreatbritain</string>\r\n" +
            "  <string>#chinatown #london #uk #greatbritain #londonisthecapitalofgreatbritain" +
            "</string>\r\n  <string>#sherlock #holmes #museum #uk #london #greatbritain</string" +
            ">\r\n  <string>#uk #london #animalsinwar #memorial #parklane</string>\r\n  <string>#" +
            "bigben #london #uk #westminster #palaceofwestminster #londonisthecapitalofgreatb" +
            "ritain</string>\r\n  <string>#london #uk #buckinghampalace #londonisthecapitalofgr" +
            "eatbritain</string>\r\n  <string>#saintpetersburg #spb #bridge #saintpeterandpaulc" +
            "athedral #sunset</string>\r\n  <string>#plane #fly #spb #saintpetersburg #russia #" +
            "clouds</string>\r\n  <string>#london #greatbritain #redbus #bus #unitedkingdom #uk" +
            "</string>\r\n  <string>#даже #не #знаю #что #написать. #спб #питер #санктпетербург" +
            " #saintpetersburg #spb</string>\r\n  <string>#петропавловскаякрепость #санктпетерб" +
            "ург #спб #питер #закат #saintpetersburg #spb</string>\r\n  <string>#санктпетербург" +
            " #тучи #закат #небо #спб #питер #saintpetersburg #spb</string>\r\n  <string>#тучи " +
            "#закат #небо #спб #питер #saintpetersburg #spb</string>\r\n  <string>#футбол #мяч " +
            "#смешнойхэштег1 #смешнойхэштег2 #спб #питер #санктпетербург #saintpetersburg #sp" +
            "b</string>\r\n  <string>#юсуповский #сад #спб #питер #санктпетербург #saintpetersb" +
            "urg #spb</string>\r\n  <string>#ботанический #сад #спб #питер #санктпетербург #бон" +
            "сай #этобонсайничегонезнаю #saintpetersburg #spb</string>\r\n  <string>#андерсенгр" +
            "ад #сосновыйбор</string>\r\n  <string>#плотина #петяярви #спб #питер #санктпетербу" +
            "рг #saintpetersburg #spb</string>\r\n  <string>#закат #питер #санктпетербург #спб " +
            "#saintpetersburg #spb</string>\r\n  <string>#гатчинский #гейзер #просто #супер #сп" +
            "б #санктпетербург #питер #saintpetersburg #spb</string>\r\n  <string>#закат #питер" +
            " #санктпетербург #спб #saintpetersburg #spb</string>\r\n  <string>#закат #питер #с" +
            "анктпетербург #спб #saintpetersburg #spb</string>\r\n  <string>#спб #питер #лофтпр" +
            "оектэтажи #фестивальенотов #енотики #щенята #енотовидной #собачки #санктпетербур" +
            "г</string>\r\n  <string>#спб #санктпетербург #питер #бременскиемузыканты</string>\r" +
            "\n  <string>#закат #питер #санктпетербург #спб #saintpetersburg #spb</string>\r\n  " +
            "<string>#спб #питер #облака #троицкиймост #saintpetersburg #spb</string>\r\n  <str" +
            "ing>#зубробизон #спб #питер #санктпетербург #saintpetersburg #spb</string>\r\n  <s" +
            "tring>#спб #питер #санктпетербург #кот #котэ #котяра #saintpetersburg #spb</stri" +
            "ng>\r\n  <string>#водопад #около #спб #saintpetersburg #spb</string>\r\n  <string>#с" +
            "пб #питер #санктпетербург #saintpetersburg #spb</string>\r\n  <string>#питер #санк" +
            "тпетербург #спб #петропавловскаякрепость #закат #saintpetersburg #spb</string>\r\n" +
            "  <string>#музейэмоций #санктпетербург #питер #СПб #saintpetersburg #spb</string" +
            ">\r\n  <string>#солнечные #часы #кронштадт</string>\r\n  <string>#мраморныйдворец #с" +
            "анктпетербург #питер #СПб #saintpetersburg #spb</string>\r\n  <string>#великийновг" +
            "ород #кораблик #ship #river #clouds</string>\r\n  <string>#великийновгород #кремль" +
            " #трава #крепость #castle</string>\r\n  <string>#спб #питер #санктпетербург #saint" +
            "petersburg #spb</string>\r\n  <string>#выборг #inception #замок #панорамагорода</s" +
            "tring>\r\n  <string>#выборг</string>\r\n  <string>#панда #крутойпробег #санктпетербу" +
            "рг #питер #СПб #saintpetersburg #spb</string>\r\n  <string>#санктпетербург #питер " +
            "#СПб #закат #saintpetersburg #spb</string>\r\n  <string>#иллюзиум #санктпетербург " +
            "#питер #СПб #saintpetersburg #spb</string>\r\n  <string>#хомяк #санктпетербург #пи" +
            "тер #СПб</string>\r\n  <string>#санктпетербург #питер #СПб</string>\r\n  <string>#ко" +
            "т #котяра #санктпетербург #питер #СПб</string>\r\n  <string>#санктпетербург #питер" +
            " #СПб #зимний #закат</string>\r\n  <string>#новыйгод #новыйгод2016 #санктпетербург" +
            " #питер #СПб</string>\r\n  <string>#новыйгод #новыйгод2016 #санктпетербург #питер " +
            "#СПб</string>\r\n  <string>#звездныевойны #starwars #хансоло #принцессалея #санктп" +
            "етербург #питер #СПб</string>\r\n  <string>#зенитчемпион, #зенитваленсия, #дзюбаго" +
            "л #зенит #санктпетербург #питер #СПб</string>\r\n  <string>#ремонтделотонкое #обож" +
            "аюхэштеги #давсёхватитуже #санктпетербург #питер #СПб</string>\r\n  <string>#санкт" +
            "петербург #питер #СПб</string>\r\n  <string>#спб #утро #туман #питер #санктпетербу" +
            "рг</string>\r\n  <string>#erarta #эрарта #санктпетербург #питер #СПб</string>\r\n  <" +
            "string>#erarta #эрарта #санктпетербург #питер #СПб</string>\r\n  <string>#haloween" +
            ", #хеллоуин, #spb #санктпетербург #питер #СПб</string>\r\n  <string>#spb #санктпет" +
            "ербург #питер #СПб #закат</string>\r\n  <string>Футбольный вечер удался! #ЗенитЛио" +
            "н , #ЗенитЧемпион #санктпетербург #питер #СПб</string>\r\n  <string>#океанариум #с" +
            "анктпетербург #питер #СПб</string>\r\n  <string>#красивый #закат #санктпетербург #" +
            "питер #СПб</string>\r\n  <string>#красивый #рассвет #санктпетербург #питер #СПб</s" +
            "tring>\r\n  <string>#мазапарк #лук #mazapark #тридебилаэтосила #санктпетербург #пи" +
            "тер #СПб</string>\r\n  <string>#сладкаяпарочка #санктпетербург #питер #СПб</string" +
            ">\r\n  <string>#розовыйслоник #рио #санктпетербург #питер #СПб</string>\r\n  <string" +
            ">#зенитчемпион #валенсиязенит #суперхалк #санктпетербург #питер #СПб</string>\r\n " +
            " <string>#санктпетербург #питер #СПб</string>\r\n  <string>#surfcoffee #санктпетер" +
            "бург #питер #спб</string>\r\n  <string>#санктпетербург #питер #СПб</string>\r\n  <st" +
            "ring>#крутой #пробег #санктпетербург #питер #СПб</string>\r\n  <string>#обед #санк" +
            "тпетербург #питер #СПб</string>\r\n  <string>#минск #красивый #город</string>\r\n</A" +
            "rrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Hashs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Hashs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("74")]
        public int Total {
            get {
                return ((int)(this["Total"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("74,73,72,71,70,69,68,67,66,65,64,63,62,61,60,59,58,57,56,54,53,52,51,50,49,48,47," +
            "46,45,44,43,41,40,39,38,37,36,35,34,33,32,31,29,28,27,26,25,24,20,19,18,17,15,14" +
            ",13,12,11,9,8,6,5,4,3,1")]
        public string IdsToUpdate {
            get {
                return ((string)(this["IdsToUpdate"]));
            }
            set {
                this["IdsToUpdate"] = value;
            }
        }
    }
}
